// gendocs generates markdown documentation from the jr Cobra command tree.
// Usage: go run ./cmd/gendocs/... <outdir>
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/sofq/jira-cli/cmd"
	"github.com/sofq/jira-cli/cmd/generated"
	jrerrors "github.com/sofq/jira-cli/internal/errors"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// ---- data model ----

// flagInfo holds extracted information about a single command flag.
type flagInfo struct {
	Name     string
	Type     string
	Required bool
	Default  string
	Usage    string
}

// verbInfo holds extracted information about a single verb (leaf command).
type verbInfo struct {
	Name    string
	Short   string
	Long    string // only set if different from Short
	Method  string
	Path    string
	HasBody bool
	Flags   []flagInfo
}

// resourcePage groups all verbs belonging to one top-level resource.
type resourcePage struct {
	Resource string
	Verbs    []verbInfo
	// SingleVerb is true when the resource has no subcommands (configure, raw, etc.)
	SingleVerb bool
}

// sidebarEntry is one entry in the VitePress sidebar JSON.
type sidebarEntry struct {
	Text string `json:"text"`
	Link string `json:"link"`
}

// exitCodeRow is one row in the error-codes table.
type exitCodeRow struct {
	ExitCode   int
	Name       string
	HTTPStatus string
	ErrorType  string
	Meaning    string
	Hint       string
}

// ---- schema lookup ----

type schemaKey struct {
	resource, verb string
}

func buildSchemaLookup() map[schemaKey]generated.SchemaOp {
	m := make(map[schemaKey]generated.SchemaOp)
	all := append(generated.AllSchemaOps(), cmd.HandWrittenSchemaOps()...)
	all = append(all, cmd.WatchSchemaOps()...)
	all = append(all, cmd.TemplateSchemaOps()...)
	all = append(all, cmd.DiffSchemaOps()...)
	for _, op := range all {
		m[schemaKey{op.Resource, op.Verb}] = op
	}
	return m
}

// ---- command tree walking ----

func extractFlags(c *cobra.Command) []flagInfo {
	var flags []flagInfo
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		// Skip the automatically added --help flag.
		if f.Name == "help" {
			return
		}
		required := false
		if ann := f.Annotations[cobra.BashCompOneRequiredFlag]; len(ann) > 0 && ann[0] == "true" {
			required = true
		}
		flags = append(flags, flagInfo{
			Name:     f.Name,
			Type:     f.Value.Type(),
			Required: required,
			Default:  f.DefValue,
			Usage:    f.Usage,
		})
	})
	return flags
}

func buildVerbInfo(c *cobra.Command, schema map[schemaKey]generated.SchemaOp, resource string) verbInfo {
	vi := verbInfo{
		Name:  c.Name(),
		Short: c.Short,
		Flags: extractFlags(c),
	}
	if c.Long != "" && c.Long != c.Short {
		vi.Long = c.Long
	}

	op, ok := schema[schemaKey{resource, c.Name()}]
	if ok {
		vi.Method = op.Method
		vi.Path = op.Path
		vi.HasBody = op.HasBody
	}
	return vi
}

func walkCommands(root *cobra.Command, schema map[schemaKey]generated.SchemaOp) []resourcePage {
	var pages []resourcePage

	for _, sub := range root.Commands() {
		if sub.Hidden || sub.Name() == "help" || sub.Name() == "completion" {
			continue
		}
		resource := sub.Name()
		children := sub.Commands()

		// Filter out hidden / help children.
		var visible []*cobra.Command
		for _, ch := range children {
			if !ch.Hidden && ch.Name() != "help" && ch.Name() != "completion" {
				visible = append(visible, ch)
			}
		}

		if len(visible) == 0 {
			// Top-level leaf command — treat the command itself as the only verb.
			vi := buildVerbInfo(sub, schema, resource)
			pages = append(pages, resourcePage{
				Resource:   resource,
				Verbs:      []verbInfo{vi},
				SingleVerb: true,
			})
		} else {
			var verbs []verbInfo
			for _, ch := range visible {
				verbs = append(verbs, buildVerbInfo(ch, schema, resource))
			}
			pages = append(pages, resourcePage{
				Resource:   resource,
				Verbs:      verbs,
				SingleVerb: false,
			})
		}
	}

	// Sort for stable output.
	sort.Slice(pages, func(i, j int) bool {
		return pages[i].Resource < pages[j].Resource
	})
	return pages
}

// ---- templates ----

const resourcePageTmpl = `<!-- Generated by jr gendocs. DO NOT EDIT. -->
# {{.Resource}}
{{if .SingleVerb}}{{range .Verbs}}
{{if .Short}}{{.Short}}{{end}}
{{if .Long}}
{{.Long}}
{{end}}
{{if .Method}}<span class="method-badge method-{{lower .Method}}">{{.Method}}</span> <code class="api-path">{{.Path}}</code>
{{end}}
{{if .Flags}}
| Flag | Type | Required | Description |
|------|------|----------|-------------|
{{range .Flags}}| ` + "`" + `--{{.Name}}` + "`" + ` | {{.Type}} | {{if .Required}}Yes{{else}}No{{end}} | {{escapePipe .Usage}} |
{{end}}
{{end}}
{{if .Flags}}**Example:**
` + "```" + `bash
jr {{$.Resource}}{{range .Flags}}{{if .Required}} --{{.Name}} <{{.Name}}>{{end}}{{end}}
` + "```" + `
{{end}}
{{end}}{{else}}{{range .Verbs}}
## {{.Name}}

{{if .Short}}{{.Short}}{{end}}
{{if .Long}}
{{.Long}}
{{end}}
{{if .Method}}<span class="method-badge method-{{lower .Method}}">{{.Method}}</span> <code class="api-path">{{.Path}}</code>
{{end}}
{{if .Flags}}
| Flag | Type | Required | Description |
|------|------|----------|-------------|
{{range .Flags}}| ` + "`" + `--{{.Name}}` + "`" + ` | {{.Type}} | {{if .Required}}Yes{{else}}No{{end}} | {{escapePipe .Usage}} |
{{end}}
{{end}}
**Example:**
` + "```" + `bash
jr {{$.Resource}} {{.Name}}{{range .Flags}}{{if .Required}} --{{.Name}} <{{.Name}}>{{end}}{{end}}
` + "```" + `
{{end}}{{end}}`

const indexPageTmpl = `<!-- Generated by jr gendocs. DO NOT EDIT. -->
# Command Reference

jr has **{{.TotalVerbs}}** commands across **{{.TotalResources}}** resources, auto-generated from Jira's OpenAPI spec.

| Resource | Commands |
|----------|----------|
{{range .Pages}}| [{{.Resource}}](/commands/{{.Resource}}) | {{verbList .Verbs}} |
{{end}}`

const errorCodesTmpl = `<!-- Generated by jr gendocs. DO NOT EDIT. -->
# Error Codes

jr uses semantic exit codes so agents can branch on errors reliably.

## Exit Codes

| Exit Code | Name | HTTP Status | Error Type | Meaning |
|-----------|------|-------------|------------|---------|
| 0 | OK | 2xx | — | Success |
{{range .Rows}}| {{.ExitCode}} | {{.Name}} | {{.HTTPStatus}} | {{.ErrorType}} | {{.Meaning}} |
{{end}}
## Error Response Format

Errors are JSON on stderr:

` + "```" + `json
{
  "error_type": "not_found",
  "status": 404,
  "message": "Issue Does Not Exist",
  "hint": "",
  "request": {"method": "GET", "path": "/rest/api/3/issue/BAD-999"}
}
` + "```" + `

## Handling Errors

{{range .Rows}}{{if .Hint}}- **{{.Name}} (exit {{.ExitCode}})**: {{.Hint}}
{{end}}{{end}}`

// ---- template helpers ----

var tmplFuncs = template.FuncMap{
	"lower": strings.ToLower,
	"escapePipe": func(s string) string {
		return strings.ReplaceAll(s, "|", "\\|")
	},
	"verbList": func(verbs []verbInfo) string {
		names := make([]string, len(verbs))
		for i, v := range verbs {
			names[i] = v.Name
		}
		return strings.Join(names, ", ")
	},
}

func renderTemplate(name, tmplStr string, data any) ([]byte, error) {
	t, err := template.New(name).Funcs(tmplFuncs).Parse(tmplStr)
	if err != nil {
		return nil, fmt.Errorf("parse template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template %s: %w", name, err)
	}
	return buf.Bytes(), nil
}

// ---- file I/O helpers ----

func writeFile(path string, data []byte) error {
	clean := filepath.Clean(path)
	if err := os.MkdirAll(filepath.Dir(clean), 0o755); err != nil {
		return err
	}
	return os.WriteFile(clean, data, 0o644) // #nosec G703 -- paths are constructed internally, not from user input
}

// ---- exit code table construction ----

var exitCodeNames = map[int]string{
	jrerrors.ExitOK:         "OK",
	jrerrors.ExitError:      "Error",
	jrerrors.ExitAuth:       "Auth",
	jrerrors.ExitNotFound:   "NotFound",
	jrerrors.ExitValidation: "Validation",
	jrerrors.ExitRateLimit:  "RateLimit",
	jrerrors.ExitConflict:   "Conflict",
	jrerrors.ExitServer:     "Server",
}

var exitCodeMeanings = map[int]string{
	jrerrors.ExitOK:         "Success",
	jrerrors.ExitError:      "General error",
	jrerrors.ExitAuth:       "Authentication or authorisation failed",
	jrerrors.ExitNotFound:   "Resource not found or gone",
	jrerrors.ExitValidation: "Invalid request (client error)",
	jrerrors.ExitRateLimit:  "Rate limited by server",
	jrerrors.ExitConflict:   "Conflict (e.g. duplicate resource)",
	jrerrors.ExitServer:     "Server-side error",
}

func buildErrorCodeRows() []exitCodeRow {
	// 200 is omitted because the static "OK | 2xx" row already covers it.
	statuses := []int{400, 401, 403, 404, 409, 410, 422, 429, 500, 502, 503}

	// Deduplicate by exit code, accumulating HTTP statuses and hints.
	type entry struct {
		exitCode   int
		statuses   []string
		errorType  string
		hints      []string
	}
	seen := make(map[int]*entry)
	hintSeen := make(map[int]map[string]bool)
	var order []int

	for _, s := range statuses {
		ec := jrerrors.ExitCodeFromStatus(s)
		et := jrerrors.ErrorTypeFromStatus(s)
		hint := jrerrors.HintFromStatus(s)

		if _, ok := seen[ec]; !ok {
			seen[ec] = &entry{exitCode: ec, errorType: et}
			hintSeen[ec] = make(map[string]bool)
			order = append(order, ec)
		}
		seen[ec].statuses = append(seen[ec].statuses, fmt.Sprintf("%d", s))
		if hint != "" && !hintSeen[ec][hint] {
			seen[ec].hints = append(seen[ec].hints, hint)
			hintSeen[ec][hint] = true
		}
	}

	// Sort rows by exit code ascending.
	sort.Ints(order)

	var rows []exitCodeRow
	for _, ec := range order {
		e := seen[ec]
		httpStatus := strings.Join(e.statuses, ", ")
		rows = append(rows, exitCodeRow{
			ExitCode:   ec,
			Name:       exitCodeNames[ec],
			HTTPStatus: httpStatus,
			ErrorType:  e.errorType,
			Meaning:    exitCodeMeanings[ec],
			Hint:       strings.Join(e.hints, " "),
		})
	}
	return rows
}

// ---- main ----

func run(outDir string) error {
	schema := buildSchemaLookup()
	root := cmd.RootCommand()
	pages := walkCommands(root, schema)

	commandsDir := filepath.Join(outDir, "commands")
	guideDir := filepath.Join(outDir, "guide")
	vitepressDir := filepath.Join(outDir, ".vitepress")

	// 0. Clean stale generated command pages so removed commands don't linger.
	if entries, err := os.ReadDir(commandsDir); err == nil {
		generated := make(map[string]bool, len(pages))
		generated["index.md"] = true
		for _, p := range pages {
			generated[p.Resource+".md"] = true
		}
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".md") && !generated[e.Name()] {
				stale := filepath.Join(commandsDir, e.Name())
				if err := os.Remove(stale); err == nil {
					fmt.Printf("  removed stale %s\n", stale)
				}
			}
		}
	}

	// 1. Per-resource pages.
	for _, page := range pages {
		data, err := renderTemplate("resource", resourcePageTmpl, page)
		if err != nil {
			return fmt.Errorf("render %s: %w", page.Resource, err)
		}
		dest := filepath.Join(commandsDir, page.Resource+".md")
		if err := writeFile(dest, data); err != nil {
			return fmt.Errorf("write %s: %w", dest, err)
		}
		fmt.Printf("  wrote %s\n", dest)
	}

	// 2. Index page.
	totalVerbs := 0
	for _, p := range pages {
		totalVerbs += len(p.Verbs)
	}
	indexData, err := renderTemplate("index", indexPageTmpl, map[string]any{
		"TotalVerbs":     totalVerbs,
		"TotalResources": len(pages),
		"Pages":          pages,
	})
	if err != nil {
		return fmt.Errorf("render index: %w", err)
	}
	indexDest := filepath.Join(commandsDir, "index.md")
	if err := writeFile(indexDest, indexData); err != nil {
		return fmt.Errorf("write %s: %w", indexDest, err)
	}
	fmt.Printf("  wrote %s\n", indexDest)

	// 3. Sidebar JSON.
	var sidebar []sidebarEntry
	for _, p := range pages {
		sidebar = append(sidebar, sidebarEntry{
			Text: p.Resource,
			Link: "/commands/" + p.Resource,
		})
	}
	sidebarJSON, err := json.MarshalIndent(sidebar, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal sidebar: %w", err)
	}
	sidebarDest := filepath.Join(vitepressDir, "sidebar-commands.json")
	if err := writeFile(sidebarDest, append(sidebarJSON, '\n')); err != nil {
		return fmt.Errorf("write %s: %w", sidebarDest, err)
	}
	fmt.Printf("  wrote %s\n", sidebarDest)

	// 4. Error codes page.
	errRows := buildErrorCodeRows()
	errData, err := renderTemplate("error-codes", errorCodesTmpl, map[string]any{
		"Rows": errRows,
	})
	if err != nil {
		return fmt.Errorf("render error-codes: %w", err)
	}
	errDest := filepath.Join(guideDir, "error-codes.md")
	if err := writeFile(errDest, errData); err != nil {
		return fmt.Errorf("write %s: %w", errDest, err)
	}
	fmt.Printf("  wrote %s\n", errDest)

	return nil
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintf(os.Stderr, "usage: gendocs <outdir>\n")
		os.Exit(1)
	}
	outDir := os.Args[1]
	fmt.Printf("generating docs into %s/\n", outDir)
	if err := run(outDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("done.")
}
