import { defineConfig } from 'vitepress'

// Try to load generated sidebar; fall back to empty array if not yet generated
let commandsSidebar: { text: string; link: string }[] = []
try {
  commandsSidebar = (await import('./sidebar-commands.json')).default
} catch {
  // Generated by `make docs-generate` — not available until first run
}

export default defineConfig({
  title: 'jr',
  description: 'Agent-friendly Jira CLI',
  base: '/jira-cli/',
  appearance: 'dark',
  // Generated command pages may contain Atlassian doc URLs that look like
  // relative links to VitePress. Ignore them rather than failing the build.
  ignoreDeadLinks: true,
  head: [
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', { href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap', rel: 'stylesheet' }],
  ],
  themeConfig: {
    logo: '/logo.svg',
    siteTitle: false,
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Commands', link: '/commands/' },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Getting Started', link: '/guide/getting-started' },
            { text: 'Filtering & Presets', link: '/guide/filtering' },
            { text: 'Discovering Commands', link: '/guide/discovery' },
            { text: 'Templates', link: '/guide/templates' },
            { text: 'Global Flags', link: '/guide/global-flags' },
            { text: 'Error Codes', link: '/guide/error-codes' },
            { text: 'Agent Integration', link: '/guide/agent-integration' },
            { text: 'Skill Setup', link: '/guide/skill-setup' },
          ],
        },
      ],
      '/commands/': [
        {
          text: 'Commands',
          items: [
            { text: 'Overview', link: '/commands/' },
            ...commandsSidebar,
          ],
        },
      ],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/sofq/jira-cli' },
    ],
    search: {
      provider: 'local',
    },
  },
})
